spring.application.name=back
server.port=3000
server.tomcat.max-http-form-post-size=20MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.datasource.url=jdbc:mysql://localhost:3306/smartdiary
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.mapper-locations=classpath*:org.example.back/**/*Mapper.xml
mybatis.type-aliases-package=org.example.back.pojo

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

sms.debug=true
sms.debug-code=123456
sms.code.expire-seconds=300
sms.code.send-interval-seconds=60

sms.access-key-id=
sms.access-key-secret=
sms.sign-name=
sms.template-code=
sms.region-id=cn-hangzhou
